# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='partner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
